# Logistic regression

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.preprocessing import LabelEncoder
from imblearn.over_sampling import SMOTE

/Users/ashademeij/opt/anaconda3/lib/python3.9/site-packages/pandas/core/computation/expressions.py:21: UserWarning: Pandas requires version '2.8.4' or newer of 'numexpr' (version '2.8.3' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
/Users/ashademeij/opt/anaconda3/lib/python3.9/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (


In [2]:
df = pd.read_csv('/Users/ashademeij/Downloads/Thesis/Code/final.csv')

In [3]:
features = ['gender', 'RACE_Asian', 'RACE_Black/African American',
            'RACE_Hispanic/Latino', 'RACE_Other', 'RACE_White', 'age_18-24', 
            'age_25-44', 'age_45-64', 'age_65-88', 
            'age_89+', 'previous_stays', 'prev_los_avg', 'Anion Gap', 
            'Bicarbonate', 'Chloride', 'Creatinine', 'Glucose', 'Hematocrit', 
            'Hemoglobin', 'MCH', 'MCHC', 'MCV', 'Magnesium', 'Platelet Count', 
            'Potassium', 'RDW', 'Red Blood Cells', 'Sodium', 'Urea Nitrogen', 
            'White Blood Cells', 'prescrip_count', 'diagnoses_num', 
            'ADM_Emergency', 'ADM_Other', 'ADM_Referral', 'ADM_Transfer', 
            'INS_Medicaid', 'INS_Medicare', 'INS_Other']

X = df[features]
y = df['los_category']

label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.2, random_state=42)

smote = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train, y_train)

In [4]:
log_reg_model = LogisticRegression(random_state=42)

param_grid = {
    'C': [0.01, 0.1, 1, 10],  # Inverse of regularization strength
    'solver': ['liblinear', 'lbfgs'],  # Optimization algorithm
    'max_iter': [100, 200, 500], 
}

grid_search = GridSearchCV(
    estimator=log_reg_model,
    param_grid=param_grid,  
    scoring='accuracy',
    cv=3,
    verbose=2,
    n_jobs=-1
)

grid_search.fit(X_train_resampled, y_train_resampled)
print(f"Best parameters found: {grid_search.best_params_}")

# Training using the best model found 
best_log_reg_model = grid_search.best_estimator_
best_log_reg_model.fit(X_train_resampled, y_train_resampled)
y_pred_log_reg = best_log_reg_model.predict(X_test)

# evaluation metrics
accuracy = accuracy_score(y_test, y_pred_log_reg)
print("Overall Accuracy of Logistic Regression Classifier:", accuracy)

conf_matrix = confusion_matrix(y_test, y_pred_log_reg)
print("Overall Confusion Matrix:")
print(conf_matrix)

y_test_labels = label_encoder.inverse_transform(y_test)
y_pred_labels = label_encoder.inverse_transform(y_pred_log_reg)

class_report_labels = classification_report(y_test_labels, y_pred_labels)
print("Overall Classification Report:")
print(class_report_labels)


Fitting 3 folds for each of 24 candidates, totalling 72 fits


/Users/ashademeij/opt/anaconda3/lib/python3.9/site-packages/pandas/core/computation/expressions.py:21: UserWarning: Pandas requires version '2.8.4' or newer of 'numexpr' (version '2.8.3' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
/Users/ashademeij/opt/anaconda3/lib/python3.9/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (
/Users/ashademeij/opt/anaconda3/lib/python3.9/site-packages/pandas/core/computation/expressions.py:21: UserWarning: Pandas requires version '2.8.4' or newer of 'numexpr' (version '2.8.3' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
/Users/ashademeij/opt/anaconda3/lib/python3.9/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import 

[CV] END .................C=0.01, max_iter=100, solver=lbfgs; total time=   0.5s


/Users/ashademeij/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/ashademeij/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.

[CV] END .................C=0.01, max_iter=100, solver=lbfgs; total time=   0.7s
[CV] END .................C=0.01, max_iter=100, solver=lbfgs; total time=   0.7s
[CV] END .............C=0.01, max_iter=100, solver=liblinear; total time=   1.4s
[CV] END .............C=0.01, max_iter=100, solver=liblinear; total time=   1.7s
[CV] END .............C=0.01, max_iter=100, solver=liblinear; total time=   1.9s
[CV] END .............C=0.01, max_iter=200, solver=liblinear; total time=   1.7s
[CV] END .............C=0.01, max_iter=200, solver=liblinear; total time=   1.8s
[CV] END .................C=0.01, max_iter=200, solver=lbfgs; total time=   1.3s


/Users/ashademeij/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/ashademeij/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.

[CV] END .................C=0.01, max_iter=200, solver=lbfgs; total time=   1.3s
[CV] END .............C=0.01, max_iter=200, solver=liblinear; total time=   2.0s
[CV] END .................C=0.01, max_iter=200, solver=lbfgs; total time=   1.3s


/Users/ashademeij/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[CV] END .............C=0.01, max_iter=500, solver=liblinear; total time=   1.5s
[CV] END .............C=0.01, max_iter=500, solver=liblinear; total time=   1.6s
[CV] END .............C=0.01, max_iter=500, solver=liblinear; total time=   1.9s


/Users/ashademeij/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[CV] END ..................C=0.1, max_iter=100, solver=lbfgs; total time=   0.6s


/Users/ashademeij/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[CV] END ..................C=0.1, max_iter=100, solver=lbfgs; total time=   0.6s


/Users/ashademeij/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/ashademeij/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.

[CV] END .................C=0.01, max_iter=500, solver=lbfgs; total time=   2.6s
[CV] END .................C=0.01, max_iter=500, solver=lbfgs; total time=   2.7s
[CV] END ..............C=0.1, max_iter=100, solver=liblinear; total time=   2.6s


/Users/ashademeij/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[CV] END .................C=0.01, max_iter=500, solver=lbfgs; total time=   2.8s
[CV] END ..................C=0.1, max_iter=100, solver=lbfgs; total time=   0.9s
[CV] END ..............C=0.1, max_iter=100, solver=liblinear; total time=   2.8s


/Users/ashademeij/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[CV] END ..................C=0.1, max_iter=200, solver=lbfgs; total time=   1.2s
[CV] END ..............C=0.1, max_iter=100, solver=liblinear; total time=   3.4s


/Users/ashademeij/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/ashademeij/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.

[CV] END ..................C=0.1, max_iter=200, solver=lbfgs; total time=   1.2s
[CV] END ..................C=0.1, max_iter=200, solver=lbfgs; total time=   1.4s
[CV] END ..............C=0.1, max_iter=200, solver=liblinear; total time=   2.7s
[CV] END ..............C=0.1, max_iter=200, solver=liblinear; total time=   2.7s
[CV] END ..............C=0.1, max_iter=500, solver=liblinear; total time=   2.5s
[CV] END ..............C=0.1, max_iter=200, solver=liblinear; total time=   3.3s
[CV] END ..............C=0.1, max_iter=500, solver=liblinear; total time=   2.5s


/Users/ashademeij/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[CV] END ..................C=0.1, max_iter=500, solver=lbfgs; total time=   2.4s


/Users/ashademeij/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/ashademeij/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.

[CV] END ....................C=1, max_iter=100, solver=lbfgs; total time=   0.4s
[CV] END ..................C=0.1, max_iter=500, solver=lbfgs; total time=   2.4s
[CV] END ..................C=0.1, max_iter=500, solver=lbfgs; total time=   2.7s
[CV] END ..............C=0.1, max_iter=500, solver=liblinear; total time=   2.9s
[CV] END ....................C=1, max_iter=100, solver=lbfgs; total time=   0.4s


/Users/ashademeij/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[CV] END ....................C=1, max_iter=100, solver=lbfgs; total time=   0.6s
[CV] END ................C=1, max_iter=100, solver=liblinear; total time=   3.6s
[CV] END ................C=1, max_iter=100, solver=liblinear; total time=   2.9s
[CV] END ....................C=1, max_iter=200, solver=lbfgs; total time=   1.2s


/Users/ashademeij/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/ashademeij/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.

[CV] END ....................C=1, max_iter=200, solver=lbfgs; total time=   1.5s


/Users/ashademeij/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[CV] END ....................C=1, max_iter=200, solver=lbfgs; total time=   1.3s
[CV] END ................C=1, max_iter=100, solver=liblinear; total time=   4.1s
[CV] END ................C=1, max_iter=200, solver=liblinear; total time=   3.6s
[CV] END ................C=1, max_iter=200, solver=liblinear; total time=   3.8s
[CV] END ................C=1, max_iter=200, solver=liblinear; total time=   4.2s
[CV] END ................C=1, max_iter=500, solver=liblinear; total time=   3.3s
[CV] END ................C=1, max_iter=500, solver=liblinear; total time=   3.7s
[CV] END ....................C=1, max_iter=500, solver=lbfgs; total time=   2.6s


/Users/ashademeij/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/ashademeij/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.

[CV] END ....................C=1, max_iter=500, solver=lbfgs; total time=   2.7s


/Users/ashademeij/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/ashademeij/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.

[CV] END ...................C=10, max_iter=100, solver=lbfgs; total time=   0.6s
[CV] END ...................C=10, max_iter=100, solver=lbfgs; total time=   0.6s


/Users/ashademeij/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/ashademeij/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.

[CV] END ...................C=10, max_iter=100, solver=lbfgs; total time=   0.7s
[CV] END ................C=1, max_iter=500, solver=liblinear; total time=   4.3s
[CV] END ....................C=1, max_iter=500, solver=lbfgs; total time=   2.9s


/Users/ashademeij/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/ashademeij/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.

[CV] END ...................C=10, max_iter=200, solver=lbfgs; total time=   1.2s
[CV] END ...................C=10, max_iter=200, solver=lbfgs; total time=   1.0s


/Users/ashademeij/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[CV] END ...................C=10, max_iter=200, solver=lbfgs; total time=   1.0s
[CV] END ...............C=10, max_iter=100, solver=liblinear; total time=   5.2s
[CV] END ...............C=10, max_iter=100, solver=liblinear; total time=   5.2s
[CV] END ...............C=10, max_iter=100, solver=liblinear; total time=   5.9s
[CV] END ...............C=10, max_iter=200, solver=liblinear; total time=   5.1s
[CV] END ...............C=10, max_iter=200, solver=liblinear; total time=   5.1s
[CV] END ...............C=10, max_iter=200, solver=liblinear; total time=   5.6s
[CV] END ...................C=10, max_iter=500, solver=lbfgs; total time=   2.4s


/Users/ashademeij/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[CV] END ...............C=10, max_iter=500, solver=liblinear; total time=   4.5s


/Users/ashademeij/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/ashademeij/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.

[CV] END ...................C=10, max_iter=500, solver=lbfgs; total time=   1.8s
[CV] END ...................C=10, max_iter=500, solver=lbfgs; total time=   1.7s
[CV] END ...............C=10, max_iter=500, solver=liblinear; total time=   3.9s
[CV] END ...............C=10, max_iter=500, solver=liblinear; total time=   3.8s
Best parameters found: {'C': 0.1, 'max_iter': 100, 'solver': 'liblinear'}
Overall Accuracy of Logistic Regression Classifier: 0.6667873958710612
Overall Confusion Matrix:
[[1092 1952]
 [ 808 4431]]
Overall Classification Report:
              precision    recall  f1-score   support

        long       0.57      0.36      0.44      3044
       short       0.69      0.85      0.76      5239

    accuracy                           0.67      8283
   macro avg       0.63      0.60      0.60      8283
weighted avg       0.65      0.67      0.64      8283



In [5]:
def evaluate_subgroup(subgroup_name, subgroup_value):
    # Filtering for the specific subgroups
    subgroup_indices = (X_test[subgroup_name] == subgroup_value)
    subgroup_X_test = X_test[subgroup_indices]
    subgroup_y_test = y_test[subgroup_indices]
    subgroup_y_pred = y_pred_log_reg[subgroup_indices]
    
    # evaluation the subgroups
    accuracy = accuracy_score(subgroup_y_test, subgroup_y_pred)
    print(f"Accuracy for {subgroup_name}={subgroup_value}: {accuracy:.4f}")
    
    conf_matrix = confusion_matrix(subgroup_y_test, subgroup_y_pred)
    print(f"Confusion Matrix for {subgroup_name}={subgroup_value}:")
    print(conf_matrix)
    
    subgroup_y_test_labels = label_encoder.inverse_transform(subgroup_y_test)
    subgroup_y_pred_labels = label_encoder.inverse_transform(subgroup_y_pred)
    
    class_report = classification_report(subgroup_y_test_labels, subgroup_y_pred_labels)
    print(f"Classification Report for {subgroup_name}={subgroup_value}:")
    print(class_report)

# gender
print("MALE")
evaluate_subgroup('gender', 0)
print("\nFEMALE")
evaluate_subgroup('gender', 1)


MALE
Accuracy for gender=0: 0.6653
Confusion Matrix for gender=0:
[[ 510  847]
 [ 401 1971]]
Classification Report for gender=0:
              precision    recall  f1-score   support

        long       0.56      0.38      0.45      1357
       short       0.70      0.83      0.76      2372

    accuracy                           0.67      3729
   macro avg       0.63      0.60      0.60      3729
weighted avg       0.65      0.67      0.65      3729


FEMALE
Accuracy for gender=1: 0.6680
Confusion Matrix for gender=1:
[[ 582 1105]
 [ 407 2460]]
Classification Report for gender=1:
              precision    recall  f1-score   support

        long       0.59      0.34      0.43      1687
       short       0.69      0.86      0.76      2867

    accuracy                           0.67      4554
   macro avg       0.64      0.60      0.60      4554
weighted avg       0.65      0.67      0.64      4554



In [6]:
# race categories
print("\nASIAN")
evaluate_subgroup('RACE_Asian', 1)
print("\nBLACK/AFRICAN AMERICAN")
evaluate_subgroup('RACE_Black/African American', 1)
print("\nHISPANIC/LATINO")
evaluate_subgroup('RACE_Hispanic/Latino', 1)
print("\nOTHER RACE")
evaluate_subgroup('RACE_Other', 1)
print("\nWHITE")
evaluate_subgroup('RACE_White', 1)


ASIAN
Accuracy for RACE_Asian=1: 0.6772
Confusion Matrix for RACE_Asian=1:
[[ 33  74]
 [ 18 160]]
Classification Report for RACE_Asian=1:
              precision    recall  f1-score   support

        long       0.65      0.31      0.42       107
       short       0.68      0.90      0.78       178

    accuracy                           0.68       285
   macro avg       0.67      0.60      0.60       285
weighted avg       0.67      0.68      0.64       285


BLACK/AFRICAN AMERICAN
Accuracy for RACE_Black/African American=1: 0.6944
Confusion Matrix for RACE_Black/African American=1:
[[129 216]
 [ 85 555]]
Classification Report for RACE_Black/African American=1:
              precision    recall  f1-score   support

        long       0.60      0.37      0.46       345
       short       0.72      0.87      0.79       640

    accuracy                           0.69       985
   macro avg       0.66      0.62      0.62       985
weighted avg       0.68      0.69      0.67       985



In [7]:
#  age groups
print("\nAGE 18-24")
evaluate_subgroup('age_18-24', 1)
print("\nAGE 25-44")
evaluate_subgroup('age_25-44', 1)
print("\nAGE 45-64")
evaluate_subgroup('age_45-64', 1)
print("\nAGE 65-88")
evaluate_subgroup('age_65-88', 1)
print("\nAGE 89+")
evaluate_subgroup('age_89+', 1)


AGE 18-24
Accuracy for age_18-24=1: 0.7553
Confusion Matrix for age_18-24=1:
[[ 11  38]
 [  8 131]]
Classification Report for age_18-24=1:
              precision    recall  f1-score   support

        long       0.58      0.22      0.32        49
       short       0.78      0.94      0.85       139

    accuracy                           0.76       188
   macro avg       0.68      0.58      0.59       188
weighted avg       0.72      0.76      0.71       188


AGE 25-44
Accuracy for age_25-44=1: 0.7037
Confusion Matrix for age_25-44=1:
[[ 77 201]
 [ 55 531]]
Classification Report for age_25-44=1:
              precision    recall  f1-score   support

        long       0.58      0.28      0.38       278
       short       0.73      0.91      0.81       586

    accuracy                           0.70       864
   macro avg       0.65      0.59      0.59       864
weighted avg       0.68      0.70      0.67       864


AGE 45-64
Accuracy for age_45-64=1: 0.6772
Confusion Matrix for a

In [8]:
# insurance types
print("\nMEDICAID")
evaluate_subgroup('INS_Medicaid', 1)
print("\nMEDICARE")
evaluate_subgroup('INS_Medicare', 1)
print("\nOTHER INSURANCE")
evaluate_subgroup('INS_Other', 1)



MEDICAID
Accuracy for INS_Medicaid=1: 0.7011
Confusion Matrix for INS_Medicaid=1:
[[ 60 155]
 [ 27 367]]
Classification Report for INS_Medicaid=1:
              precision    recall  f1-score   support

        long       0.69      0.28      0.40       215
       short       0.70      0.93      0.80       394

    accuracy                           0.70       609
   macro avg       0.70      0.61      0.60       609
weighted avg       0.70      0.70      0.66       609


MEDICARE
Accuracy for INS_Medicare=1: 0.6456
Confusion Matrix for INS_Medicare=1:
[[ 596  898]
 [ 473 1902]]
Classification Report for INS_Medicare=1:
              precision    recall  f1-score   support

        long       0.56      0.40      0.47      1494
       short       0.68      0.80      0.74      2375

    accuracy                           0.65      3869
   macro avg       0.62      0.60      0.60      3869
weighted avg       0.63      0.65      0.63      3869


OTHER INSURANCE
Accuracy for INS_Other=1: 0.6

# Model with exclusion of protected attributes

In [9]:
protected_attributes = ['gender', 'RACE_Asian', 'RACE_Black/African American',
                 'RACE_Hispanic/Latino', 'RACE_Other', 'RACE_White', 'age_18-24',
                 'age_25-44', 'age_45-64', 'age_65-88', 'age_89+', 'INS_Medicaid', 'INS_Medicare', 'INS_Other']

featuresNew = [feat for feat in features if feat not in protected_attributes]

X_without_protected = df[featuresNew]
y = df['los_category']

X_train_np, X_test_np, y_train, y_test = train_test_split(X_without_protected, y_encoded, test_size=0.2, random_state=42)

smote = SMOTE(random_state=42)
X_train_resampled_np, y_train_resampled = smote.fit_resample(X_train_np, y_train)

In [10]:
best_log_reg_model.fit(X_train_resampled_np, y_train_resampled)
y_pred_rf_np = best_log_reg_model.predict(X_test_np)

accuracy_np = accuracy_score(y_test, y_pred_rf_np)
print("Overall Accuracy of LR Classifier without protected attributes:", accuracy_np)

conf_matrix_np = confusion_matrix(y_test, y_pred_rf_np)
print("Overall Confusion Matrix without protected attributes:")
print(conf_matrix_np)

label_encoder = LabelEncoder()
label_encoder.fit(y_encoded)

y_test_labels = label_encoder.inverse_transform(y_test)
y_pred_labels = label_encoder.inverse_transform(y_pred_rf_np)

class_report_labels = classification_report(y_test_labels, y_pred_labels)
print("Overall Classification Report without protected attributes:")
print(class_report_labels)

Overall Accuracy of LR Classifier without protected attributes: 0.6583363515634432
Overall Confusion Matrix without protected attributes:
[[1365 1679]
 [1151 4088]]
Overall Classification Report without protected attributes:
              precision    recall  f1-score   support

           0       0.54      0.45      0.49      3044
           1       0.71      0.78      0.74      5239

    accuracy                           0.66      8283
   macro avg       0.63      0.61      0.62      8283
weighted avg       0.65      0.66      0.65      8283



In [11]:
# calculating metrics per protected attribute
def calculate_protected_attribute_metrics(results, protected_attribute):
    if protected_attribute == 'gender':
        unique_values = results[protected_attribute].unique()
        for value in unique_values:
            subset = results[results[protected_attribute] == value]
            y_test_subset = subset['y_test']
            y_pred_subset = subset['y_pred']

            accuracy = accuracy_score(y_test_subset, y_pred_subset)
            conf_matrix = confusion_matrix(y_test_subset, y_pred_subset)

            y_test_labels = label_encoder.inverse_transform(y_test_subset)
            y_pred_labels = label_encoder.inverse_transform(y_pred_subset)
            class_report = classification_report(y_test_labels, y_pred_labels)

            gender_label = 'Female' if value == 1 else 'Male'
            print(f"Metrics for {protected_attribute} = {gender_label}:")
            print(f"Overall Accuracy: {accuracy}")
            print("Confusion Matrix:")
            print(conf_matrix)
            print("Classification Report:")
            print(class_report)
            print("\n")
    else:
        unique_values = results[protected_attribute].unique()
        for value in unique_values:
          if value == 1:
            subset = results[results[protected_attribute] == value]
            y_test_subset = subset['y_test']
            y_pred_subset = subset['y_pred']

            accuracy = accuracy_score(y_test_subset, y_pred_subset)

            conf_matrix = confusion_matrix(y_test_subset, y_pred_subset)

            y_test_labels = label_encoder.inverse_transform(y_test_subset)
            y_pred_labels = label_encoder.inverse_transform(y_pred_subset)
            class_report = classification_report(y_test_labels, y_pred_labels)

            print(f"Metrics for {protected_attribute} = {value}:")
            print(f"Overall Accuracy: {accuracy}")
            print("Confusion Matrix:")
            print(conf_matrix)
            print("Classification Report:")
            print(class_report)
            print("\n")

X_test_with_protected = df.loc[X_test_np.index][protected_attributes].reset_index(drop=True)
results = pd.DataFrame({'y_test': y_test, 'y_pred': y_pred_rf_np})
results = results.join(X_test_with_protected)

# Evaluation metrics for each protected attribute
for protected_attribute in protected_attributes:
    calculate_protected_attribute_metrics(results, protected_attribute)


Metrics for gender = Female:
Overall Accuracy: 0.6572244180939834
Confusion Matrix:
[[ 777  910]
 [ 651 2216]]
Classification Report:
              precision    recall  f1-score   support

           0       0.54      0.46      0.50      1687
           1       0.71      0.77      0.74      2867

    accuracy                           0.66      4554
   macro avg       0.63      0.62      0.62      4554
weighted avg       0.65      0.66      0.65      4554



Metrics for gender = Male:
Overall Accuracy: 0.6596942880128721
Confusion Matrix:
[[ 588  769]
 [ 500 1872]]
Classification Report:
              precision    recall  f1-score   support

           0       0.54      0.43      0.48      1357
           1       0.71      0.79      0.75      2372

    accuracy                           0.66      3729
   macro avg       0.62      0.61      0.61      3729
weighted avg       0.65      0.66      0.65      3729



Metrics for RACE_Asian = 1:
Overall Accuracy: 0.6736842105263158
Confusion M